Upgraded to SDL2 and dosbox-staging
Hopefully fixes multimonitors and sound

diff --git a/launcher/launcher b/launcher/launcher
--- a/launcher/launcher
+++ b/launcher/launcher
@@ -1,77 +1,27 @@
 #!/bin/bash
 
 set -e
+set -o pipefail
+
+fail () {
+	yad --width=300 --title="$1" --text="$2" --text-align=center --button=gtk-ok:1 --center
+}
 
 GAMEDIR=epic_pinball_shareware
 
-if [ "$SNAP_ARCH" == "amd64" ]; then
-  ARCH="x86_64-linux-gnu"
-elif [ "$SNAP_ARCH" == "armhf" ]; then
-  ARCH="arm-linux-gnueabihf"
-elif [ "$SNAP_ARCH" == "arm64" ]; then
-  ARCH="aarch64-linux-gnu"
-else
-   ARCH="$SNAP_ARCH-linux-gnu"
-fi
-
-export LD_LIBRARY_PATH=$SNAP/usr/lib/$ARCH:$LD_LIBRARY_PATH
-
-# XKB config
-export XKB_CONFIG_ROOT=$SNAP/usr/share/X11/xkb
-
-export LD_LIBRARY_PATH=$SNAP/usr/lib/$ARCH/pulseaudio:$LD_LIBRARY_PATH
-
-# Mesa Libs
-export LD_LIBRARY_PATH=$SNAP/usr/lib/$ARCH/mesa:$LD_LIBRARY_PATH
-export LD_LIBRARY_PATH=$SNAP/usr/lib/$ARCH/mesa-egl:$LD_LIBRARY_PATH
-
-# XDG Config
-export XDG_CONFIG_DIRS=$SNAP/etc/xdg:$XDG_CONFIG_DIRS
-export XDG_CONFIG_DIRS=$SNAP/usr/xdg:$XDG_CONFIG_DIRS
-# Note: this doesn't seem to work, QML's LocalStorage either ignores
-# or fails to use $SNAP_USER_DATA if defined here
-export XDG_DATA_DIRS=$SNAP_USER_DATA:$XDG_DATA_DIRS
-export XDG_DATA_DIRS=$SNAP/usr/share:$XDG_DATA_DIRS
-
-# Workaround in snapd for proprietary nVidia drivers mounts the drivers in
-# /var/lib/snapd/lib/gl that needs to be in LD_LIBRARY_PATH
-export LD_LIBRARY_PATH=/var/lib/snapd/lib/gl:$LD_LIBRARY_PATH
-
-# Not good, needed for fontconfig
-export XDG_DATA_HOME=$SNAP_USER_DATA/usr/share
-
-# Font Config
-export FONTCONFIG_PATH=$SNAP/etc/fonts/config.d
-export FONTCONFIG_FILE=$SNAP/etc/fonts/fonts.conf
-
-# Tell libGL where to find the drivers
-export LIBGL_DRIVERS_PATH=$SNAP/usr/lib/$ARCH/dri
-
-# Necessary for the SDK to find the translations directory
-export APP_DIR=$SNAP
-
-# Use GTK styling for running under Unity 7
-export DESKTOP_SESSION=ubuntu
-export XDG_SESSION_DESKTOP=ubuntu
-export XDG_CURRENT_DESKTOP=Unity
-
-#export LIBGL_DEBUG="verbose"
-
-export XLOCALEDIR="$SNAP/usr/share/X11/locale"
-export LOCPATH="$SNAP/usr/lib/locale"
-
-SDL_AUDIODRIVER=pulse
-
 if [ ! -d $SNAP_USER_DATA/$GAMEDIR/shareware ];
 then
-  echo "Game directory doesn't exist"
-  echo "Creating directory"
-  mkdir -p $SNAP_USER_DATA/$GAMEDIR
-  echo "Copying game to directory"
-  cd $SNAP_USER_DATA/$GAMEDIR
-  guiluurve download
-  wget https://archive.org/download/epic_pinball_11/epic_pinball.zip -t 5 --timeout 10 || guiluurve nodownload
-  unzip -d shareware epic_pinball.zip || guiluurve nozip
+	echo "Game directory does not exist"
+	echo "Creating directory"
+	mkdir -p $SNAP_USER_DATA/$GAMEDIR
+	echo "Copying game to directory"
+	cd $SNAP_USER_DATA/$GAMEDIR
+	wget https://archive.org/download/epic_pinball_11/epic_pinball.zip -t 5 --timeout 10 2>&1 | \
+	perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
+	yad --progress --title="Downloading Epic Pinball" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape \
+	|| fail "Network Error" "Could not access network to download game files.\n\nPlease check the network status."
+	unzip -d shareware epic_pinball.zip \
+	|| fail "Error" "Could not extract game files.\n\nThe download may have been corrupted"
 fi
 
 cd $SNAP_USER_DATA/$GAMEDIR
@@ -79,11 +29,9 @@ cp $SNAP/dosbox_distrib.conf .
 
 if [ -f $SNAP_USER_DATA/$GAMEDIR/dosbox.conf ];
 then
-  echo "Using custom configuration"
-  dosbox -conf dosbox.conf
+	echo "Using custom configuration"
+	dosbox -conf dosbox.conf
 else
-  echo "Using default configuration"
-  dosbox -conf dosbox_distrib.conf
+	echo "Using default configuration"
+	dosbox -conf dosbox_distrib.conf
 fi
-
-xrandr -s 0
